import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "tools" / "update_readme_svg.py"


def test_readme_svg_has_a_deterministic_generated_text_layer():
    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--check"],
        cwd=ROOT, capture_output=True, text=True, timeout=20)
    assert result.returncode == 0, result.stdout + result.stderr

    svg = (ROOT / "arte-ascii-readme.svg").read_text(encoding="utf-8")
    assert "generated by tools/update_readme_svg.py" in svg
    assert "MAK" in svg
