#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Buttons that actually run something, behind a gate made of generated data.

The ask, in the user's words: buttons so that tomorrow he can hand the work to
any free agent -- or press them himself -- instead of copying commands into a
terminal. That means the hub has to be able to RUN a command, which is a door,
and a door needs a gate.

The gate is built from `context/comandos.json`, which is GENERATED by
introspecting the real CLI. That matters more than it looks: an allow-list
written by hand is exactly what this repo hit three times on 2026-07-31 --
`refutar.py`'s provider tuple, `codex_lib`'s chain map, `CLAVES_VISION` -- a
list that stopped matching reality and discarded in silence. A generated gate
cannot drift from the thing it guards.

Three properties, each pinned below:

1. A command that is not in the manifest never runs. There is no free-form
   command string, so nothing outside the CLI can be reached.
2. `destructivo: True` needs an explicit `confirmar`. So does `null` --
   "nobody classified it" is NOT "it is safe", and treating it as safe is the
   same defect as a default that fills an absence.
3. What the gate refuses, it refuses with the reason of THAT case. Telling an
   unclassified command that it "changes things" would assert what nobody
   measured.
"""
import json
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent
HUB = RAIZ / "src" / "flujo" / "web" / "hub.py"
FUENTE = HUB.read_text(encoding="utf-8")


def _handler(root):
    """The method under test WITHOUT starting the server.

    `__new__` skips BaseHTTPRequestHandler's `__init__`, which would open a
    socket. Testing a gate should not need a port -- and starting the app opens
    a browser window, which is noise on the machine of someone working."""
    from flujo.web.hub import HubRequestHandler
    h = HubRequestHandler.__new__(HubRequestHandler)
    h.root = root
    return h


def test_the_gate_is_generated_not_hand_written():
    """The gate reads the generated manifest. A list written into this file
    would go stale and discard in silence, which is the defect this repo hit
    three times in one day."""
    assert "_leer_manifiesto_comandos" in FUENTE
    assert "context" in FUENTE and "comandos.json" in FUENTE
    # and there is no second hand-written command list inside the hub
    assert "COMANDOS_PERMITIDOS" not in FUENTE


def test_an_unknown_command_never_runs():
    h = _handler(RAIZ)
    r = h._correr_comando({"cmd": "rm -rf /", "confirmar": True})
    assert r["_http"] == 400
    assert "no esta en" in r["error"]
    assert "rc" not in r, "no se ejecuto nada"


def test_a_free_form_string_cannot_smuggle_a_second_command():
    """No shell: the command is split and passed as a list."""
    h = _handler(RAIZ)
    r = h._correr_comando({"cmd": "version; rm -rf /", "confirmar": True})
    assert r["_http"] == 400
    assert "subprocess.run(orden" in FUENTE or "subprocess.run(" in FUENTE
    assert "shell=True" not in FUENTE, "a shell turns an argument into a command"


def test_a_declared_destructive_command_demands_confirmation():
    h = _handler(RAIZ)
    r = h._correr_comando({"cmd": "airdrop apply"})
    assert r["_http"] == 409
    assert r["destructivo"] is True
    assert "declarado como destructivo" in r["error"]


def test_an_unclassified_command_also_demands_confirmation():
    """`null` is not `false`. Treating "nobody classified it" as "it is safe"
    is the same defect as a default that fills an absence."""
    manifiesto = json.loads(
        (RAIZ / "context" / "comandos.json").read_text(encoding="utf-8"))
    sin_clasificar = next(c["cmd"] for c in manifiesto["comandos"]
                          if c["destructivo"] is None)
    h = _handler(RAIZ)
    r = h._correr_comando({"cmd": sin_clasificar})
    assert r["_http"] == 409
    assert r["destructivo"] is None
    assert "nadie lo clasifico" in r["error"]
    # and it does NOT say it changes things, because nobody measured that
    assert "cambia cosas" not in r["error"]


def test_the_argument_list_is_bounded():
    h = _handler(RAIZ)
    r = h._correr_comando({"cmd": "version", "confirmar": True,
                           "args": ["x"] * 50})
    assert r["_http"] == 400
    assert "hasta 20" in r["error"]


def test_a_missing_manifest_says_so_instead_of_looking_empty(tmp_path):
    """Zero buttons reads as "there is nothing to do". If the manifest is
    missing, it says so and explains how to generate it."""
    h = _handler(tmp_path)
    d = h._leer_manifiesto_comandos()
    assert d["comandos"] == []
    assert "error" in d and "gen_mapa_comandos" in d["error"]


def test_truncated_output_declares_that_it_was_truncated():
    """A silent truncation reads as "that was everything it said"."""
    assert "recortado" in FUENTE


# --------------------------------------------------- the failure notice

def test_a_failed_command_reports_whether_anyone_was_told():
    """ntfy is for when nobody is at the machine. At the keyboard the rc and
    the stderr are right there; away from it, a button that failed in silence
    is worse than no button. What is pinned here is that the answer says
    whether the notice ACTUALLY went out -- claiming `true` on a no-op would be
    the same defect as a default filling an absence."""
    import os
    os.environ.pop("FLUJO_NTFY_TOPIC", None)
    h = _handler(RAIZ)
    r = h._correr_comando({"cmd": "version", "confirmar": True,
                           "args": ["--no-existe"]})
    assert r["ok"] is False and r["rc"] != 0
    assert r["aviso_enviado"] is False, (
        "sin topic configurado nadie fue avisado, y eso se dice")


def test_a_successful_command_notifies_nobody():
    """Success is not news. A notification per button press is how a channel
    gets muted in a week, and then the failures do not arrive either."""
    h = _handler(RAIZ)
    r = h._correr_comando({"cmd": "version", "confirmar": True})
    assert r["ok"] is True
    assert r["aviso_enviado"] is False


def test_the_channel_state_travels_with_the_manifest():
    """The interface has to be able to say 'nobody will be told' instead of
    implying somebody will."""
    assert '"aviso"' in FUENTE or 'manifiesto["aviso"]' in FUENTE
    assert "FLUJO_NTFY_TOPIC" in FUENTE


def test_the_title_header_is_folded_to_ascii():
    """A gotcha MAK already paid for in July: the ntfy `Title` header rejects
    accents. The BODY keeps them -- it is what a human reads."""
    from flujo.aviso import _ascii
    assert _ascii("reducción de daño") == "reduccion de dano"
    assert _ascii("") == ""


def test_a_notice_never_takes_down_what_it_reports():
    """Best effort: a failing notification must not turn a reported failure
    into a crash."""
    from flujo.aviso import avisar
    assert avisar("x", topic="") is False
    fuente = (RAIZ / "src" / "flujo" / "aviso.py").read_text(encoding="utf-8")
    assert "except Exception" in fuente and "return False" in fuente
