// productoras.ts - reference adapter for the standalone Plano/Rider bundle.
//
// The embedded projection is generated by tools/gen_rd_standalone.py from
// data/productoras/*.json and knowledge/venues/*.yaml through the same
// flujo.rd.panel allowlist used by the hub. Keeping this adapter derived from
// that projection prevents the standalone list from becoming an old manual
// snapshot when a producer or artist is added or corrected.

import rdDbEmbebida from './rdDbEmbebida.json';

export interface ProductoraRef {
  slug: string;
  name: string;
}

interface EmbeddedProductora {
  slug: string;
  nombre: string;
}

const embeddedProductoras = (rdDbEmbebida as {
  productoras?: EmbeddedProductora[];
}).productoras ?? [];

export const RD_PRODUCTORAS: ProductoraRef[] = embeddedProductoras.map(({ slug, nombre }) => ({
  slug,
  name: nombre,
}));
