// Frame-cost instrument for the campo skin: deterministic, headless, offline.
//
// The handoff of 2026-07-30 left the links drawn "always, faint, by weight"
// with the neighbour index built once, and pinned the defect class (all pairs
// every frame) by static tests -- but the actual per-frame COST of the
// published skin had never been executed and counted. "NOT measured: fps on a
// phone" stays true: a phone cannot be measured from CI. What CAN be measured
// deterministically is the WORK per frame -- drawn segments, canvas geometry
// ops, neighbour-index size -- because counts do not depend on the machine.
// Milliseconds are reported as informative context only, never pinned.
//
// Technique: same as tools/iskvw_piel_smoke.mjs -- the PUBLISHED file's own
// inline script runs in node inside a vm with DOM stubs; nothing in the skin
// is modified. The 2d context is a counting proxy: every stroke() is one drawn
// segment (the link loops do beginPath/moveTo/lineTo/stroke per link), every
// arc/gradient/fillText is node-drawing work. Scenarios are REAL: the repo's
// campo.json (today's live fallback, 219 works) and the publish-time
// archivo.json substrate (--archivo, generated by gen_archivo_iskvw.py exactly
// as .github/workflows/publicar_iskvw.yml does), entered through the skin's
// own seed model `#semilla=&centro=&escala=` plus the pinch aperture.
//
// Usage:
//   node tools/iskvw_piel_medir.mjs [--archivo path/to/archivo.json]
//                                   [--frames N] [--json]
// Prints a table and, as the LAST line, one machine-readable JSON object.
// Invoked by tests/test_iskvw_piel_medir.py, which pins the counts.
import { readFileSync, existsSync } from "node:fs";
import vm from "node:vm";
import { performance } from "node:perf_hooks";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const raiz = join(dirname(fileURLToPath(import.meta.url)), "..");

let archivoPath = null, frames = 5, warmup = 3, soloJson = false;
const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === "--archivo") archivoPath = resolve(argv[++i]);
  else if (argv[i] === "--frames") frames = Number(argv[++i]) || 5;
  else if (argv[i] === "--json") soloJson = true;
  else { console.error(`unknown argument: ${argv[i]}`); process.exit(2); }
}
if (!archivoPath) {
  const porDefecto = join(raiz, "iskvw", "datos", "archivo.json");
  if (existsSync(porDefecto)) archivoPath = porDefecto;
}

const html = readFileSync(join(raiz, "iskvw", "piel", "campo", "index.html"), "utf8");
const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1]);
if (!scripts.length) { console.error("no inline <script> found"); process.exit(2); }

const noop = () => {};

// One fresh sandbox per scenario: the skin keeps its state in module-level
// globals (E, NODOS, VECINOS...), so reusing a context would leak one
// scenario's state into the next and the ordering would stop being neutral.
function arrancarPiel({ substrate, hash }) {
  // Canvas op counters. stroke() is the segment count: both link loops in the
  // skin emit exactly one stroke per drawn segment. lineTo is kept as a
  // cross-check (it must equal stroke for pure segment drawing).
  const cnt = { segmentos: 0, lineas: 0, arcos: 0, gradientes: 0, textos: 0 };
  const resetCnt = () => { for (const k of Object.keys(cnt)) cnt[k] = 0; };

  const ctx2d = new Proxy({}, {
    get: (t, k) => {
      if (k === "canvas") return canvas;
      if (k === "createRadialGradient" || k === "createLinearGradient")
        return () => { cnt.gradientes++; return { addColorStop: noop }; };
      if (k === "fillText") return () => { cnt.textos++; };
      if (k === "measureText") return () => ({ width: 10 });
      if (k === "getImageData") return () => ({ data: new Uint8ClampedArray(4) });
      if (k === "arc") return () => { cnt.arcos++; };
      if (k === "lineTo") return () => { cnt.lineas++; };
      if (k === "stroke") return () => { cnt.segmentos++; };
      return noop;
    },
    set: () => true,
  });
  const canvas = {
    getContext: () => ctx2d, width: 800, height: 600,
    clientWidth: 800, clientHeight: 600,
    style: {}, addEventListener: noop, removeEventListener: noop,
    getBoundingClientRect: () => ({ left: 0, top: 0, width: 800, height: 600 }),
  };
  const el = () => ({
    classList: { add: noop, remove: noop, toggle: noop, contains: () => false },
    style: {}, addEventListener: noop, removeEventListener: noop,
    textContent: "", innerHTML: "", appendChild: noop, setAttribute: noop,
    getBoundingClientRect: () => ({ left: 0, top: 0, width: 800, height: 600 }),
  });
  const elements = new Map();
  const getEl = id => {
    if (id === "c") return canvas;
    if (!elements.has(id)) elements.set(id, el());
    return elements.get(id);
  };

  let rafQueue = [];
  const sandbox = {
    console, Math, JSON, Date, performance,
    URLSearchParams,                   // the seed model parses the hash with it
    requestAnimationFrame: cb => { rafQueue.push(cb); return rafQueue.length; },
    cancelAnimationFrame: noop,
    setTimeout: () => 0, clearTimeout: noop, setInterval: () => 0, clearInterval: noop,
    // The fetch stub decides WHICH substrate this scenario measures:
    // "archivo" serves the generated archivo.json (pieces + links, the
    // publish-time path); "campo" 404s it so the skin degrades to the
    // repo's campo.json exactly like today's live site does without it.
    fetch: async (url) => {
      const u = String(url);
      if (/datos\/archivo\.json$/.test(u)) {
        if (substrate === "archivo" && archivoPath) {
          try {
            const txt = readFileSync(archivoPath, "utf8");
            return { ok: true, json: async () => JSON.parse(txt) };
          } catch { return { ok: false, json: async () => ({}) }; }
        }
        return { ok: false, json: async () => ({}) };
      }
      const m = u.match(/datos\/(campo|obras)\.json$/);
      if (m) {
        try {
          const txt = readFileSync(join(raiz, "iskvw", "datos", `${m[1]}.json`), "utf8");
          return { ok: true, json: async () => JSON.parse(txt) };
        } catch { return { ok: false, json: async () => ({}) }; }
      }
      return { ok: false, json: async () => ({}) };
    },
    addEventListener: noop, removeEventListener: noop, history: { replaceState: noop },
    location: { hash, href: "http://medir.local/" },
    navigator: { maxTouchPoints: 0 },
    devicePixelRatio: 1, innerWidth: 800, innerHeight: 600,
  };
  sandbox.window = sandbox;
  sandbox.document = {
    getElementById: getEl,
    querySelector: () => el(), querySelectorAll: () => [],
    addEventListener: noop, removeEventListener: noop,
    body: el(), documentElement: el(), hidden: false,
    createElement: () => el(),
  };

  const context = vm.createContext(sandbox);
  let failed = null;
  const onRejection = (e) => { failed = failed || e; };
  process.on("unhandledRejection", onRejection);
  try {
    for (const src of scripts) vm.runInContext(src, context, { timeout: 10000 });
  } catch (e) { failed = e; }

  return {
    context, cnt, resetCnt,
    fallo: () => failed,
    cerrar: () => process.removeListener("unhandledRejection", onRejection),
    tomarFrames: () => { const b = rafQueue; rafQueue = []; return b; },
  };
}

const espera = ms => new Promise(r => setTimeout(r, ms));

async function medirEscenario(substrate, nombre, hash, pinch) {
  const piel = arrancarPiel({ substrate, hash });
  await espera(25);                    // arrancar() is async: drain the loader
  if (piel.fallo()) throw piel.fallo();

  // Freeze the gesture so the frame is the FIELD frame, pure: no velocity, no
  // resolution (tocando=true keeps resolver() out), aperture set by pinch --
  // the same variable the real pinch gesture writes, so diafragma() sees a
  // state a visitor can actually produce.
  vm.runInContext(
    `E.vel = 0; E.suave = 0; E.tocando = true; E.pinch = ${pinch};`,
    piel.context);

  const tiempos = [], porFrame = [];
  for (let i = 0; i < warmup + frames; i++) {
    piel.resetCnt();
    const lote = piel.tomarFrames();
    if (!lote.length) throw new Error(`no frame queued at step ${i} (${nombre})`);
    const t0 = performance.now();
    for (const cb of lote) cb(t0);
    const dt = performance.now() - t0;
    if (piel.fallo()) throw piel.fallo();
    if (i >= warmup) { tiempos.push(dt); porFrame.push({ ...piel.cnt }); }
  }

  // Determinism is the contract: with the gesture frozen, every measured frame
  // must do identical work. Random jitter moves pixels, never counts.
  const primero = JSON.stringify(porFrame[0]);
  for (const f of porFrame) {
    if (JSON.stringify(f) !== primero)
      throw new Error(`unstable counts in ${nombre}: ${primero} vs ${JSON.stringify(f)}`);
  }

  const estado = JSON.parse(vm.runInContext(`JSON.stringify({
    nodos: NODOS.length,
    largo: Math.round(LARGO),
    indice_entradas: VECINOS.reduce((a, l) => a + l.length, 0),
    vinculos_indexados: VECINOS.reduce((a, l) => a + l.length, 0) / 4,
    pos: Math.round(E.pos),
  })`, piel.context));
  piel.cerrar();

  tiempos.sort((a, b) => a - b);
  return {
    sustrato: substrate, escenario: nombre, hash, pinch,
    ...estado, ...porFrame[0],
    // n*(n-1)/2: what the all-against-all defect would cost on this substrate.
    todos_los_pares: estado.nodos * (estado.nodos - 1) / 2,
    ms_mediana: Number(tiempos[Math.floor(tiempos.length / 2)].toFixed(3)),
  };
}

// Probe boot: read the field the skin actually built (ids, ys, LARGO) so the
// scenario grid is derived from the REAL data, not from a copy of its math.
async function sondear(substrate) {
  const piel = arrancarPiel({ substrate, hash: "" });
  await espera(25);
  if (piel.fallo()) throw piel.fallo();
  piel.tomarFrames();                  // discard: the probe draws nothing
  const campo = JSON.parse(vm.runInContext(`JSON.stringify({
    ids: NODOS.map(n => n.obra.id),
    ys: NODOS.map(n => Math.round(n.y)),
    largo: Math.round(LARGO),
  })`, piel.context));
  piel.cerrar();
  return campo;
}

// Densest reading position: the y that puts the most nodes inside the OPEN
// diaphragm band (alcance = 260 + 1*1500, from diafragma() at s=1). This is
// the worst case the ceiling test guards.
function centroDenso(ys) {
  const ALCANCE_ABIERTO = 1760;
  const orden = [...ys].sort((a, b) => a - b);
  let mejor = orden[0] || 0, mejorN = -1;
  for (const c of orden) {
    const n = orden.filter(y => Math.abs(y - c) <= ALCANCE_ABIERTO).length;
    if (n > mejorN) { mejorN = n; mejor = c; }   // ties: lowest y, deterministic
  }
  return { centro: mejor, en_banda: mejorN };
}

const substratos = ["campo"];
if (archivoPath) substratos.unshift("archivo");

const filas = [];
for (const s of substratos) {
  const campo = await sondear(s);
  if (!campo.ids.length) { console.error(`empty field for substrate ${s}`); process.exit(1); }
  const denso = centroDenso(campo.ys);
  const primera = campo.ids[0];
  const medio = Math.round(campo.largo / 2);
  // The grid: entry seed as shipped, then centers across the field, closed and
  // open apertures, the densest band (worst case), and one lateral scale.
  const grilla = [
    ["entrada cerrada",  `#semilla=${primera}`, 0],
    ["entrada abierta",  `#semilla=${primera}`, 1],
    ["medio abierto",    `#centro=${medio}`, 1],
    ["denso cerrado",    `#centro=${denso.centro}`, 0],
    ["denso medio",      `#centro=${denso.centro}`, 0.5],
    ["denso abierto",    `#centro=${denso.centro}`, 1],
    ["denso escalado",   `#centro=${denso.centro}&escala=0.8`, 1],
  ];
  for (const [nombre, hash, pinch] of grilla)
    filas.push(await medirEscenario(s, nombre, hash, pinch));
}

if (!soloJson) {
  const cab = ["sustrato", "escenario", "pinch", "nodos", "vinculos_indexados",
               "segmentos", "gradientes", "arcos", "textos", "ms_mediana"];
  const anchos = cab.map(c => Math.max(c.length,
    ...filas.map(f => String(f[c === "vinculos_indexados" ? "vinculos_indexados" : c]).length)));
  const linea = vals => vals.map((v, i) => String(v).padEnd(anchos[i] + 2)).join("");
  console.log(linea(cab));
  for (const f of filas)
    console.log(linea(cab.map(c => f[c])));
  const peor = Math.max(...filas.map(f => f.segmentos));
  console.log(`\nworst segments/frame across the grid: ${peor}` +
    ` (all-against-all on the same substrates would be ` +
    `${filas.map(f => f.todos_los_pares).reduce((a, b) => Math.max(a, b), 0)} pairs/frame)`);
  console.log("counts are deterministic; ms are this machine's, informative only\n");
}
console.log(JSON.stringify({
  version: 1,
  archivo: archivoPath ? true : false,
  frames_medidos: frames,
  escenarios: filas,
  peor_segmentos: Math.max(...filas.map(f => f.segmentos)),
}));
