#!/usr/bin/env python3
"""Refresh the README data inside the preserved ASCII vessel artwork."""
from __future__ import annotations

import argparse
from html import escape, unescape
import itertools
from pathlib import Path
import re
import unicodedata


ROOT = Path(__file__).resolve().parents[1]
SVG_PATH = ROOT / "arte-ascii-readme.svg"
README_PATH = ROOT / "README.md"
TEXT_BLOCK_RE = re.compile(
    r"(?P<open><text\b[^>]*class=[\"'][^\"']*"
    r"(?:text-container|readme-source(?:-static)?)[^\"']*[\"'][^>]*>)"
    r"(?P<body>.*?)"
    r"(?P<close></text>)",
    re.DOTALL,
)
TSPAN_LEAF_RE = re.compile(
    r"(?P<open><tspan\b[^>]*>)(?P<content>[^<]*)(?P<close></tspan>)",
    re.DOTALL,
)


def _ascii_line(line: str) -> str:
    folded = unicodedata.normalize("NFKD", line)
    folded = folded.encode("ascii", "ignore").decode("ascii")
    folded = re.sub(r"\s+", " ", folded.strip())
    return folded[:112]


def digest(readme: str) -> list[str]:
    """Build a compact status layer from the current README, not old artwork."""
    selected = [
        "VIBECODEINE / FLUJO / DIMENSIONS OF ORDER",
        "Git checkpoint: main only; runtime truth: Windows + MAK local state",
        "MAK / RD / Portfolio: sovereign organisms; Git: reviewed transport",
        "MAK = Linux inbox + research + codex + hub",
        "traceability: work_id -> evidence -> decision -> next_action",
        "README: ASCII vessel / text as material / animation as artwork",
    ]
    for raw in readme.splitlines():
        line = _ascii_line(raw)
        if not line:
            continue
        folded = line.lower()
        if "four canonical branches" in folded:
            continue
        if any(token in folded for token in (
                "main", "mak", "iskvw", "rd", "svg", "branch",
                "artist", "readme", "hub", "ledger", "evidence")):
            if line not in selected:
                selected.append(line)
        if len(selected) >= 18:
            break
    return selected


def data_stream(lines: list[str]) -> str:
    """Turn the status layer into safe visible ASCII glyphs."""
    source = "|".join(lines)
    source = re.sub(r"[^A-Za-z0-9_./:+|=-]", "", source)
    return source or "VIBECODEINE"


def _render_layer(body: str, stream: str) -> str:
    glyphs = itertools.cycle(stream)

    def replace(match: re.Match[str]) -> str:
        content = match.group("content")
        if not unescape(content).strip():
            return match.group(0)
        return match.group("open") + escape(next(glyphs)) + match.group("close")

    return TSPAN_LEAF_RE.sub(replace, body)


def expected_svg(svg: str, readme: str) -> str:
    blocks = list(TEXT_BLOCK_RE.finditer(svg))
    if len(blocks) < 1:
        raise ValueError("readme_svg_ascii_layers_missing")
    stream = data_stream(digest(readme))
    replacements = []
    for match in blocks:
        body = _render_layer(match.group("body"), stream)
        replacements.append(match.group("open") + body + match.group("close"))

    output = svg
    for match, replacement in reversed(list(zip(blocks, replacements))):
        output = output[:match.start()] + replacement + output[match.end():]
    output = re.sub(
        r"<title>.*?</title>",
        "<title>VIBECODEINE - current repo ASCII vessel</title>",
        output,
        count=1,
        flags=re.DOTALL,
    )
    output = re.sub(
        r"<desc\b[^>]*>.*?</desc>",
        "<desc id=\"desc\">ASCII data from the current VIBECODEINE repository and MAK runtime, carried by a preserved double cup.</desc>",
        output,
        count=1,
        flags=re.DOTALL,
    )
    output = re.sub(
        r"\s*<!-- generated by tools/update_readme_svg\.py -->",
        "",
        output,
    )
    output = output.replace(
        "</desc>",
        "</desc>\n<!-- generated by tools/update_readme_svg.py -->",
        1,
    )
    return output


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args(argv)
    current = SVG_PATH.read_text(encoding="utf-8")
    readme = README_PATH.read_text(encoding="utf-8")
    expected = expected_svg(current, readme)
    if args.check:
        return 0 if current == expected else 2
    target = args.output or SVG_PATH
    target.write_text(expected, encoding="utf-8")
    print(target)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
