#!/usr/bin/env python3
"""Refresh the README artwork text from the current operational README."""
from __future__ import annotations

import argparse
from html import escape
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SVG_PATH = ROOT / "arte-ascii-readme.svg"
README_PATH = ROOT / "README.md"
TEXT_OPEN = '<text x="10" y="20" xml:space="preserve">'
TEXT_CLOSE = "</text>"
MARKER = "<!-- generated by tools/update_readme_svg.py -->"


def _ascii_line(line: str) -> str:
    return re.sub(r"\s+", " ", line.strip())[:112]


def digest(readme: str) -> list[str]:
    """Select a compact, readable status layer without copying the README."""
    selected = []
    for raw in readme.splitlines():
        line = _ascii_line(raw)
        if not line:
            continue
        if line.startswith("#") or line.startswith("```"):
            selected.append(line)
            continue
        folded = line.lower()
        if any(token in folded for token in (
                "main", "mak", "iskvw", "rd", "svg", "opportun",
                "fondart", "branch", "artist", "readme")):
            selected.append(line)
        if len(selected) >= 58:
            break
    return selected[:58]


def render_text(lines: list[str], indent: str = "      ") -> str:
    parts = [indent + MARKER,
             indent + '<text x="10" y="20" xml:space="preserve">']
    for index, line in enumerate(lines):
        prefix = indent + "<tspan x=\"10\" dy=\"%s\">" % (
            "0" if index == 0 else "12")
        parts.append(prefix + escape(line) + "</tspan>")
    parts.append(indent + "</text>")
    return "\n".join(parts)


def expected_svg(svg: str, readme: str) -> str:
    text_start = svg.find(TEXT_OPEN)
    if text_start < 0:
        raise ValueError("readme_svg_text_layer_missing")
    text_line_start = svg.rfind("\n", 0, text_start) + 1
    marker_start = svg.rfind(MARKER, 0, text_start)
    if marker_start >= 0 and "\n" in svg[marker_start:text_start]:
        start = svg.rfind("\n", 0, marker_start) + 1
        indent = svg[start:marker_start]
    else:
        start = text_line_start
        indent = svg[start:text_start]
    end = svg.find(TEXT_CLOSE, text_start)
    if end < 0:
        raise ValueError("readme_svg_text_layer_unclosed")
    end += len(TEXT_CLOSE)
    generated = render_text(digest(readme), indent=indent)
    return svg[:start] + generated + svg[end:]


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    current = SVG_PATH.read_text(encoding="utf-8")
    readme = README_PATH.read_text(encoding="utf-8")
    expected = expected_svg(current, readme)
    if args.check:
        return 0 if current == expected else 2
    SVG_PATH.write_text(expected, encoding="utf-8")
    print(SVG_PATH)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
