// CommandPanel -- buttons that RUN, instead of commands to copy.
//
// What this replaced, and why it had to go: a hand-written list of ~30 command
// STRINGS with a copy-to-clipboard button on each. Two defects in one file.
//
// 1. It was a hand-kept list next to a real CLI, so it drifted. The CLI has 91
//    invocable commands; that list showed 30, and nothing ever compared them.
//    Same shape this repo hit three times on 2026-07-31 (`refutar.py`'s provider
//    tuple, `codex_lib`'s chain map, `CLAVES_VISION`): a list written by hand
//    that stopped matching reality and dropped the rest in silence.
// 2. Copying is not operating. The user's ask was buttons "para que el agente
//    pueda ser yo" -- something he, or a free agent tomorrow, can press without
//    a terminal. A clipboard button still needs a terminal.
//
// So the panel now draws itself from `context/comandos.json`, GENERATED by
// introspecting the real CLI (`tools/gen_mapa_comandos.py`, kept honest by
// `tests/test_comandos_manifiesto.py`). It cannot drift from what exists.
//
// Three things it refuses to fake:
//   - Without a backend there are no buttons, and it SAYS so. A disabled button
//     that looks pressable is worse than an explained absence.
//   - `destructivo: null` is not `false`. Unclassified asks for confirmation
//     with the reason of THAT case -- claiming "cambia cosas" about a command
//     nobody classified would assert what nobody measured. The backend enforces
//     this too; the interface just stops being the one that lies.
//   - A command that is not `listo` still shows, with what it lacks. Hiding it
//     would read as "does not exist".
//
// Visible copy stays in Spanish: this is what the user reads.

import { useEffect, useMemo, useState } from 'react';
import { TerminalSquare, Play, ShieldAlert, Search, BellOff, Bell } from 'lucide-react';

interface Comando {
  cmd: string;
  invocacion: string;
  grupo: string;
  desc: string;
  requiere: string;
  estado: string;
  destructivo: boolean | null;
}

interface Manifiesto {
  formato?: string;
  total?: number;
  comandos: Comando[];
  error?: string;
  aviso?: { configurado?: boolean; como?: string };
}

interface Resultado {
  cmd?: string;
  rc?: number;
  ok?: boolean;
  stdout?: string;
  stderr?: string;
  aviso_enviado?: boolean;
  error?: string;
  destructivo?: boolean | null;
  corriendo?: boolean;
}

const esFile = typeof window !== 'undefined' && window.location.protocol === 'file:';

function Salida({ r }: { r: Resultado }) {
  if (r.corriendo) return <p className="mt-2 text-xs text-amber-400">corriendo...</p>;
  if (r.error) {
    return (
      <p className="mt-2 rounded border border-amber-700/50 bg-amber-950/30 p-2 text-xs text-amber-300">
        {r.error}
      </p>
    );
  }
  const cuerpo = [r.stdout, r.stderr].filter(Boolean).join('\n').trim();
  return (
    <div className="mt-2 space-y-1">
      <p className={`text-xs font-bold ${r.ok ? 'text-emerald-400' : 'text-red-400'}`}>
        rc={r.rc} {r.ok ? 'ok' : 'fallo'}
        {!r.ok && (
          <span className="ml-2 font-normal text-zinc-500">
            {r.aviso_enviado ? 'aviso enviado al telefono' : 'nadie fue avisado'}
          </span>
        )}
      </p>
      {cuerpo ? (
        <pre className="max-h-64 overflow-auto whitespace-pre-wrap rounded bg-black/50 p-2 font-mono text-[11px] text-zinc-300">
          {cuerpo}
        </pre>
      ) : (
        <p className="text-xs text-zinc-600">sin salida</p>
      )}
    </div>
  );
}

function Fila({
  c,
  resultado,
  correr,
}: {
  c: Comando;
  resultado?: Resultado;
  correr: (c: Comando, args: string[], confirmar: boolean) => void;
}) {
  const [args, setArgs] = useState('');
  const [pidiendo, setPidiendo] = useState(false);
  const listo = c.estado === 'listo';
  // `false` no existe hoy en el manifiesto, pero el dia que exista, un comando
  // declarado inocuo corre de una. Lo demas pide confirmacion.
  const necesitaConfirmar = c.destructivo !== false;

  const lanzar = () => {
    const partidos = args.trim() ? args.trim().split(/\s+/) : [];
    if (necesitaConfirmar && !pidiendo) {
      setPidiendo(true);
      return;
    }
    setPidiendo(false);
    correr(c, partidos, necesitaConfirmar);
  };

  return (
    <div className="rounded-lg border border-zinc-800/60 bg-black/30 p-3">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <p className="truncate font-mono text-xs text-zinc-200">{c.invocacion}</p>
          {c.desc && <p className="mt-0.5 text-[11px] leading-snug text-zinc-500">{c.desc}</p>}
          {!listo && (
            <p className="mt-1 text-[11px] text-amber-500/90">{c.estado}</p>
          )}
        </div>
        <button
          onClick={lanzar}
          disabled={esFile || resultado?.corriendo}
          title={esFile ? 'Sin backend: abre con py -m flujo app' : 'Correr'}
          className={`flex shrink-0 items-center gap-1 rounded-md border px-2.5 py-1.5 text-xs font-bold transition disabled:opacity-40 ${
            pidiendo
              ? 'border-red-600/70 bg-red-950/40 text-red-300 hover:bg-red-900/50'
              : 'border-zinc-700 bg-zinc-900 text-zinc-300 hover:border-zinc-500 hover:text-white'
          }`}
        >
          {pidiendo ? <ShieldAlert className="h-3.5 w-3.5" /> : <Play className="h-3.5 w-3.5" />}
          {pidiendo ? 'Confirmar' : 'Correr'}
        </button>
      </div>

      {pidiendo && (
        <p className="mt-2 text-[11px] text-red-300/90">
          {c.destructivo === true
            ? 'Esta declarado como destructivo.'
            : 'Nadie lo clasifico todavia, y sin clasificar no se asume que sea seguro.'}{' '}
          Apreta otra vez para correrlo.
        </p>
      )}

      <input
        value={args}
        onChange={e => setArgs(e.target.value)}
        placeholder="argumentos (opcional)"
        spellCheck={false}
        className="mt-2 w-full rounded border border-zinc-800 bg-black/40 px-2 py-1 font-mono text-[11px] text-zinc-300 placeholder:text-zinc-700 focus:border-zinc-600 focus:outline-none"
      />

      {resultado && <Salida r={resultado} />}
    </div>
  );
}

export default function CommandPanel() {
  const [man, setMan] = useState<Manifiesto | null>(null);
  const [fallo, setFallo] = useState('');
  const [busqueda, setBusqueda] = useState('');
  const [soloListos, setSoloListos] = useState(false);
  const [resultados, setResultados] = useState<Record<string, Resultado>>({});

  useEffect(() => {
    if (esFile) return;
    fetch('/api/comandos')
      .then(r => r.json())
      .then(setMan)
      .catch(e => setFallo(String(e)));
  }, []);

  const grupos = useMemo(() => {
    const q = busqueda.trim().toLowerCase();
    const lista = (man?.comandos || []).filter(c => {
      if (soloListos && c.estado !== 'listo') return false;
      if (!q) return true;
      return (c.cmd + ' ' + c.desc + ' ' + c.grupo).toLowerCase().includes(q);
    });
    const por = new Map<string, Comando[]>();
    for (const c of lista) {
      const k = c.grupo || 'general';
      if (!por.has(k)) por.set(k, []);
      por.get(k)!.push(c);
    }
    return [...por.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  }, [man, busqueda, soloListos]);

  async function correr(c: Comando, args: string[], confirmar: boolean) {
    setResultados(p => ({ ...p, [c.cmd]: { corriendo: true } }));
    try {
      const r = await fetch('/api/comando', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ cmd: c.cmd, args, confirmar }),
      });
      const salida: Resultado = await r.json();
      setResultados(p => ({ ...p, [c.cmd]: salida }));
    } catch (e) {
      setResultados(p => ({ ...p, [c.cmd]: { error: String(e) } }));
    }
  }

  const total = man?.comandos?.length ?? 0;
  const listos = (man?.comandos || []).filter(c => c.estado === 'listo').length;

  return (
    <div className="space-y-5">
      <div>
        <h1 className="flex items-center gap-2 text-2xl font-black">
          <TerminalSquare className="h-6 w-6" /> Comandos
        </h1>
        <p className="mt-1 text-sm text-zinc-500">
          {total
            ? `${total} comandos del CLI real, ${listos} listos para correr. Sale de context/comandos.json, generado por introspeccion.`
            : 'El CLI como botones.'}
        </p>
      </div>

      {esFile && (
        <p className="rounded-lg border border-amber-700/50 bg-amber-950/30 p-3 text-sm text-amber-300">
          Este HTML esta abierto como archivo, sin backend: los botones no pueden
          correr nada. Abrelo con <code className="font-mono">py -m flujo app</code>.
        </p>
      )}
      {fallo && (
        <p className="rounded-lg border border-red-800/50 bg-red-950/30 p-3 text-sm text-red-300">
          No pude leer /api/comandos: {fallo}
        </p>
      )}
      {man?.error && (
        <p className="rounded-lg border border-amber-700/50 bg-amber-950/30 p-3 text-sm text-amber-300">
          {man.error}
        </p>
      )}

      {man?.aviso && (
        <p className="flex items-center gap-2 text-xs text-zinc-500">
          {man.aviso.configurado ? (
            <>
              <Bell className="h-3.5 w-3.5 text-emerald-500" />
              Si un comando falla, sale un aviso al telefono.
            </>
          ) : (
            <>
              <BellOff className="h-3.5 w-3.5 text-zinc-600" />
              Si un comando falla lejos del PC, nadie se entera: {man.aviso.como}
            </>
          )}
        </p>
      )}

      {!esFile && total > 0 && (
        <div className="flex flex-wrap items-center gap-3">
          <div className="flex flex-1 items-center gap-2 rounded-lg border border-zinc-800 bg-black/30 px-3 py-2">
            <Search className="h-4 w-4 shrink-0 text-zinc-600" />
            <input
              value={busqueda}
              onChange={e => setBusqueda(e.target.value)}
              placeholder="buscar comando"
              className="w-full bg-transparent text-sm text-zinc-200 placeholder:text-zinc-600 focus:outline-none"
            />
          </div>
          <label className="flex cursor-pointer items-center gap-2 text-xs text-zinc-400">
            <input
              type="checkbox"
              checked={soloListos}
              onChange={e => setSoloListos(e.target.checked)}
            />
            solo los que estan listos
          </label>
        </div>
      )}

      <div className="grid gap-5 lg:grid-cols-2">
        {grupos.map(([grupo, comandos]) => (
          <section key={grupo} className="rounded-xl border border-zinc-800/60 bg-zinc-900/40 p-4">
            <h2 className="mb-3 text-sm font-bold uppercase tracking-widest text-zinc-400">
              {grupo} <span className="ml-1 font-normal text-zinc-600">{comandos.length}</span>
            </h2>
            <div className="space-y-2">
              {comandos.map(c => (
                <Fila key={c.cmd} c={c} resultado={resultados[c.cmd]} correr={correr} />
              ))}
            </div>
          </section>
        ))}
      </div>

      {!esFile && !man && !fallo && <p className="text-sm text-zinc-600">cargando...</p>}
      {total > 0 && grupos.length === 0 && (
        <p className="text-sm text-zinc-600">Ningun comando coincide con ese filtro.</p>
      )}
    </div>
  );
}
